### ISSUE TITLE
Cannot install LUnit dependency on LabVIEW 2023 Q3 evaluation

### ISSUE THREAD

**Issue by gt-thetic** [Astemes/astemes-lunit#1]
I have a clean copy of LabVIEW 2023 Q3 in evaluation mode, on Windows 10 Enterprise evaluation (All in a VM where I have full admin rights).  I wanted to try out LUnit before committing to it.  After trying to install LUnit from VIPM, I'm given a red triangle saying missing dependency.  
![Screenshot 2023-12-06 120010](https://github.com/Astemes/astemes-lunit/assets/131265119/124167b7-a6da-47aa-bacd-d3b24e1b5b84)
When I try to install the missing dependency, I get a message saying that ```package astemes_lib_lunit_system-1.3.9.17``` could not be installed.
![Screenshot 2023-12-06 120028](https://github.com/Astemes/astemes-lunit/assets/131265119/b326b4bf-bbb9-4f90-bf95-f6717a29facc)
I have experienced the same issue on a similar installation on fully activated Windows, not in a VM.

**Comment by antsundq** [comment]
Hi,
Thanks for bringing this to my attention. The system package contains the CLI, which is installed into the ../LabVIEWCLI directory and not ../LabVIEW 20xx. I’ll try to reproduce this on my end and get back to you. 

Without this dependency, you should still be able to use LUnit without restrictions from the LabVIEW development environment. However, the native CLI interface will not function. 

/Anton

**Comment by gt-thetic** [comment]
> Hi, Thanks for bringing this to my attention. The system package contains the CLI, which is installed into the ../LabVIEWCLI directory and not ../LabVIEW 20xx. I’ll try to reproduce this on my end and get back to you.
> 
> Without this dependency, you should still be able to use LUnit without restrictions from the LabVIEW development environment. However, the native CLI interface will not function.
> 
> /Anton

Thanks for informing me that LUnit still works even after this issue.  I can see it in my Tools menu now and can create the 'new test case'.

**Comment by antsundq** [comment]
Great! Happy testing. 

If you need some guidance getting started, there is some docs available e.g. here: https://lunit.astemes.com/10_Basics/

**Comment by antsundq** [comment]
I'm having problems replicating this issue. Are you still seeing it with the 1.4.x release?

If it is still an issue, we'll need to get some support from the vipm-community.

**Comment by gt-thetic** [comment]
I've used version 1.4.15.17.vip from the release on github on a fresh installation of LV 2023 Q3 64-bit, before activation, and I still received this message.
![image](https://github.com/Astemes/astemes-lunit/assets/131265119/d02d7c43-d973-4000-9efd-ce572d82501e)
I also went to the activated installation of LV 2023 Q3 64-bit where the latest VIPM was version was already installed.  I then tried 1.4.15.17 as above, and I still had the same result.

**Comment by antsundq** [comment]
I forwarded the question to vipm forum and Jim explained a plausible reason for this error. Could you confirm if it applies to your situation?

See: 
https://forums.vipm.io/topic/7841-missing-system-dependency-when-installing-package/?_fromLogin=1

/Anton

**Comment by r-good** [comment]
I had this error just today on 32-bit, but I have this fully installed with dependencies in 64-bit. Wonder if this is part of the issue?

**Comment by r-good** [comment]
I'll confirm that running VIPM as Admin fixed this problem and installed the dependency

**Comment by antsundq** [comment]
Issue resolved by moving the CLI operations causing this into a separate package as of version 1.4.20

**Comment by antsundq** [comment]
https://github.com/Astemes/astemes-lunit-global-fixture/
