### ISSUE TITLE
Remove requirement for starting the name of a test VI with TEST

### ISSUE THREAD

**Issue by antsundq** [Astemes/astemes-lunit#12]
In the original implementation of xUnit, test methods are identified by the four letters "test" in the beginning of the name. In many modern implementations for text based languages, this requirement has been dropped and tests are identified by annotations.

One common obstacle when starting to use LUnit is that this requirement is not known by the developer and the tests are not run, because they are not found.

As of v 1.6.15 LUnit also supports the prefix "verify". 

Given these facts, it feels like a natural next step to drop the requirement for a prefix all together. Instead any public method belonging to a test case class would be considered as a test method. This should not cause problems as there is no reason to have public methods in a test case class which are not tests.

This would cause the problems that any public method in existing test case classes would be identified as a test. It would not report a result, unless there is an assertion within the VI. 

To improve the developer experience we could finally add a result message to any test which does not assert anything to either add an assertion or make it private. 

What do you think?

**Comment by j-medland** [comment]
I don't see this imposing any issues with my usage and moving away from relying on vi naming conventions sounds sensible.

**Comment by antsundq** [comment]
Appreciate your feedback John, thanks. 

Trying to figure out if there is any use case which would be impaired by such a change.

**Comment by antsundq** [comment]
I realized that there are problems with dynamic dispatch methods. These are used for extending the framework, but also for *e.g.* the setup.vi and teardown.vi methods.. So I do not want to make these dynamic dispatch methods be identified as tests, but there are valid cases for using dynamic dispatch vi:s as test vi:s (although not recommended for most use cases).

As I see it we can either:
1. Require dynamic dispatch methods to start with the letters test, while loosening the requirement for static methods
2. Discard the idea and keep using the prefix

I kind of like the first alternative, but it makes for a possible awkward situation when someone tries to create a dynamic method and it won't run. This is likely an edge case, but it would be frustrating..

**Comment by j-medland** [comment]
Can you just exclude any overrides of the `Test Case.lvclass` - any child class wouldn't be able to have members called `setup.vi` or `teardown.vi` that they intended to use as tests anyway?

**Comment by antsundq** [comment]
That was my first thought. But there might be cases where a test case class needs to define new dynamic vis to be overridden. 

This would be rare, but as an example, I'm considering making an add-on for parametrized tests. Then I might want to have an override for defining the parameters. Not sure yet if this is the way to go, but the idea is that you would override one vi to define the sets of parameters you want to test and then every test in that class would be called with these parameters. The problem I'm trying to solve here is duplication of test code. 

But then again, treating dynamic and static vis differently really bothers me. Even if using dynamic vis should be very rare, it might end up confusing a beginner.

**Comment by j-medland** [comment]
Ah, yeah. I wasn't thinking about longer inheritance chains.

Maybe just sticking with "Test in the name" convention is fine - at least it is straightforward opt-in to get a VI tested and can be easily communicated.

🤷‍♂️

**Comment by stagg54** [comment]
I haven't chimed in because I don't have a real strong opinion.

I'm not opposed if you want to do it. 

For the Parameters VI and the setup/teardown, couldn't you make those private or protected or something? I guess that would be a breaking change, but it's a breaking change that the compiler would tell you about and it may be tedious but not hard or complicated to fix.

**Comment by antsundq** [comment]
Yeah, personally I don't mind the prefix, it is not a big deal. 

There is technically no requirement for a prefix, so it feels a bit arbitrary. And I've seen beginners getting confused by it. 

I think the easiest way would be to only require the prefix when using dynamic vi:s. Using dynamic tests is a rare edge case anyway.

**Comment by antsundq** [comment]
Limiting the access scope won't work as the methods must be visible to the framework. And I do not like community scope.

**Comment by stagg54** [comment]
what about just a virtual folder - maybe  call it ignored or something. Anything in that folder is not a test?

**Comment by antsundq** [comment]
Could be done, but I don't know if it is clearer. And our Parameterized test would start looking like this: 

![image](https://github.com/user-attachments/assets/f4377bda-2bc1-42e0-a22b-61caa6fb9687)

And the implementation could end up being relatively slow.

The more I consider it, the less of a problem it feels to leave the prefix requirement there for dynamic methods. I would like to discourage people from using them anyway, as they cannot be edited if the LUnit UI is open. And starting from the template, you would not end up with a dynamic method, unless you really wanted to. And for that kind of user, I think it would be enough to have the prefix requirement spelled out in the documentation.

Again, having the test in the name I think is a sensible default, as it makes it easy to ignore test code when looking for callers, etc. But removing the requirement would make it easier for new developers to pick up the tool, as there is one less detail to keep in mind. And I've seen first hand the frustration of "why is it not running my tests..".

**Comment by antsundq** [comment]
After letting this simmer for a bit, I've decided on removing the requirement for the *test* prefix for static dispatch test vi:s.

This means that any test utility method in public scope will be shown in the UI. However, if they do not contain assertions they will not cause failures. It will only look weird.
The fix to this is however straightforward - just restrict the access scope.
