### ISSUE TITLE
Add test from right click menu on virtual folder

### ISSUE THREAD

**Issue by pettaa123** [Astemes/astemes-lunit#13]
Thanks for creating this test framework. I think it is very intuitive to use. I organize the tests in virtual folders. Is it possible to create the test cases directly in a virtual folder? I would love to see add LUnit Test Case on the right click menu on a virtual folder.

**Comment by antsundq** [comment]
First off, thanks for posting the idea and contributing to this project.

I also arrange my tests in virtual folders, and could see the convenience of such a right click menu option. It would not interfere with other functionality and the only drawback I see immediately is slight cluttering of the IDE and the cost of one more feature to maintain.

In my own workflow, I tend to keep the test case I am working on at the top level of the project for convenience. When done with it and moving on to the next, I put it in a virtual folder to run it for regression testing. For large projects, I might have the regression tests in a separate project file to speed up load times. 

I'll have a look when I find some time if this could easily be implemented by generalizing the current test case generation code. If so, it could probably be added as a feature with minimal new code.

**Comment by pettaa123** [comment]
Drag n Drop is not very well done in the LabVIEW IDE (the tree has to be opened beforehand). If you have a larger project it is very possible that you dan't display the test case on top level and the code to test at the same time. So you have to use the vertical slider, which is too annoying.

**Comment by antsundq** [comment]
Okay, so do you have deep hierarchies of virtual folders? 

I usually have the "tests" virtual folder on the top level of the project. There should never be any dependencies pointing from the code to the tests, and keeping them on the top level it is simple to exclude from builds etc. For this reason, I'd not like to place the test code with the production code. 

Also, for really large projects, I tend to use nested project files to keep load times short. 

But overall, I agree that your suggestion about adding the right-click menu could be convenient.

**Comment by antsundq** [comment]
Sorry for not being able to prioritize this and for the moment I will close this request as not planned. If you still feel this being an important issue, feel free to implement and create a pull request.
