### ISSUE TITLE
Change method template name to test case name

### ISSUE THREAD

**Issue by pettaa123** [Astemes/astemes-lunit#14]
It would improve my workflow if the method template created in a test case would hold the name of the the case.

**Comment by antsundq** [comment]
Thanks for sharing the idea.

Could you explain your workflow a bit regarding this? I am trying to understand the reason for naming test methods after test cases. 

This is something I would not do myself, as I would regard that as a redundant duplication. Just for context, if I have a test case called "Voltage Supply Test.lvclass", I would not name my tests "Test Voltage Supply Test Sets Output when Turned of.vi". This would make the qualified name of the test "Voltage Supply Test.lvclass:Test Voltage Supply Test Sets Output when Turned of.vi". I'd rather use the more concise "Voltage Supply Test.lvclass:Test Sets Output when Turned of.vi". And what if I decide to rename my test case class to "Power Supply Test.lvclass", would I go and rename each test method also? 

Not saying that what you are suggesting is in any way wrong, just that it might not be a behavior we want to "force" upon users through templates. In my own workflow, I name (and often rename) tests starting from the template as I go. Having the template being called template also helps new users get started.

**Comment by pettaa123** [comment]
I see your points. Until now I created a test case for every method. You see now why I would have loved to create the test cases on the virtual folders directly.

I will adapt my workflow to your suggestion.
