### ISSUE TITLE
Boolean output on the API call?

### ISSUE THREAD

**Issue by stagg54** [Astemes/astemes-lunit#15]
Can we add a Passed? boolean output to the API call that is True if all tests results are either "Skipped" or "Passed"?

Right now I'm just parsing the string output (see below) and that seems rather inefficient.

Since it is simply adding an output, it shouldn't be a breaking change. 

![image](https://github.com/user-attachments/assets/d8a02bf2-b33b-4ef6-9656-fcdca05e52b5)

**Comment by stagg54** [comment]
I cloned the repo and was going to make a pullrequest, however there were some missing VIs (even after I installed the vipc).

See image.
![image](https://github.com/user-attachments/assets/cf22c787-2eed-45c8-8507-775fc2908708)

**Comment by antsundq** [comment]
Right, yes that would make sense. 

Would it make sense to make it a string? Then we could distinguish fails from errors. It would still show "Passed" if all tests are either passed or skipped.

![image](https://github.com/user-attachments/assets/ab200483-3129-4ac4-a6ff-66d55a81d473)

Regarding the issues you see cloning the repo, it seems like I have some namespace issues I need to sort out. Will have a look at that when I find some time.

**Comment by antsundq** [comment]
Hey, sorry for the delay. This is now added to the API:
![image](https://github.com/user-attachments/assets/8ccd755b-2b4c-4591-a86c-deb0cf36c55e)
It is in the version found here: https://github.com/Astemes/astemes-lunit/releases/tag/v1.7.6
Will post to VIPM in the near future.

**Comment by stagg54** [comment]
Awesome! Thank you!

-- Samuel Taggart LabVIEW Champion, DQMH Trusted Advisor CLA, CTD,CPI SAS Workshops sasworkshops.com 412-216-8789
