### ISSUE TITLE
test discovery issue with parameterized tests

### ISSUE THREAD

**Issue by stagg54** [Astemes/astemes-lunit#18]
Not sure if this belongs here or in the parameterized repo.

As you can see, something isn't working quite right here. It detecting the private vi as test, but not detecting the other public VI?
![image](https://github.com/user-attachments/assets/42a6b94e-4f35-4bd2-8f02-078996859c96)

![image](https://github.com/user-attachments/assets/1a7dc4d5-c1e2-4c16-aa83-821ccd3c56de)

**Comment by stagg54** [comment]
![image](https://github.com/user-attachments/assets/cdc0438d-91cf-4a44-a6da-2d597fe6c4b6)

**Comment by antsundq** [comment]
My guess is that the change to private is not seen. 

- I assume you have saved the class
- try marking the test case class as not separate compile code. That is for the lvclass file, not the vi:s. 

If this does not help, could you share the code?

**Comment by stagg54** [comment]
try here. Day12 folder.
https://gitlab.com/stagg54/AOC24LV/-/tree/391e6955f2c0328c2db6a4181c21d6691b849e70

Class is not seen by project toolbar at all. Running from the right click menu on the class gives the same result as above.

Went to change separate compiled code and realized that by default it was unchecked. Must be something with your template.  It is checked in the project file. I would assume either it would always be checked or it would honor the project setting. Created another new parameterized test and noticed the same thing. Maybe that is a separate issue.

Either way, it appears to generate the same results in terms of the result window regardless of the state of the checkbox.

**Comment by stagg54** [comment]
The newly created parameterized test class has the same problem with discovering the private VI. So it wasn't just that one instance. It's some deeper problem just FYI.

**Comment by antsundq** [comment]
Ah, I think it occurred to me what I messed up. Will make an update.

**Comment by antsundq** [comment]
Moved this here:
https://github.com/Astemes/astemes-lunit-parameterized-test/issues/5

**Comment by antsundq** [comment]
Fixed and published to vipm 
https://www.vipm.io/package/astemes_lib_lunit_parameterized_add_on/
