### ISSUE TITLE
Can we make the Pass If and other assertions public instead of protected?

### ISSUE THREAD

**Issue by stagg54** [Astemes/astemes-lunit#2]
I'm trying to write some generic test helper functions that call some of the assertions. I can't do that easily because they are protected and my test helper functions exist outside a test class in another library. I can still access the protected VIs using the decorator pattern to expose the protected methods (so they aren't really as protected as one might think), but it is a pain in the butt.

**Comment by antsundq** [comment]
Sure thing, I do not see why not. 

The reason they are protected is because there has not been any reason for making them public. Your use case changes this.

**Comment by antsundq** [comment]
Here: https://github.com/Astemes/astemes-lunit/releases/tag/v1.3.12

Will update to VIPM at some point when it's been used some.
