### ISSUE TITLE
Run All Crashes LabVIEW 2020 64-bit

### ISSUE THREAD

**Issue by napowelson** [Astemes/astemes-lunit#9]
Similar to the other bug, I can run individual tests via the right click menu, but run all either doesn't find any tests in the sample projects, or crashes.  Attached is the crash log.
[df4084ac-2f22-40d7-9d37-158b4c503bc5.zip](https://github.com/Astemes/astemes-lunit/files/14812052/df4084ac-2f22-40d7-9d37-158b4c503bc5.zip)

**Comment by antsundq** [comment]
Hi, 
This is very strange. There are no useful details on why this happens in the crash log. Other than it is caused by something else than what was reported in [issue 8](https://github.com/Astemes/astemes-lunit/issues/8). 

I asked around some and got a few pointers, but nothing conclusive. I made an attempt at a fix, could you try if [this release](https://github.com/Astemes/astemes-lunit/releases/tag/untagged-1c15d51f56a3c338c6da) resolves the issue?

**Comment by napowelson** [comment]
Oh, I was just about to download it and test it out. We have this happening on all instances we've attempted to install and use it on. (my system and two other coworkers). 

We are using latest LabVIEW 2020 64-bit.

**Comment by antsundq** [comment]
Okay, thanks for this information. Do you have some other vipm toolkits installed which could be causing this? There has to be something with your setups, as I am not able to reproduce it on any system. 

Does it crash both from the toolbar Run All icon and from the Tools>Lunit>Run All menu item?

**Comment by antsundq** [comment]
Here is a new version where I fixed my earlier mix-up:
[V1.4.26](https://github.com/Astemes/astemes-lunit/releases/tag/v1.4.26)

I'm trying to force the tests to run in the app instance of the active project, but this is kind of black magic so not sure if it helps.

**Comment by napowelson** [comment]
Here is a list of all the VIPM packages I have installed:
WebSockets-2.0.1.40
Unicity-1.1.0.6
UI Tools-1.4.1.74
TDD Caraya Project Template-1.0.0.7
SQLite Library-1.15.0.114
Robust CSV-1.1.0.4
OpenG Variant Data Library-5.0.0.27
OpenG String Library-5.0.0.25
OpenG File Library-4.0.1.22
OpenG Error Library-4.2.0.23
OpenG Array Library-4.1.1.14
OpenG Application Control Library-4.1.0.7
NI Syslog Library-1.3.3.27
NI Super Simple Neural Networks-2.4.0.1
NI String Tools Library-2.0.0.5
NI State Pattern Actor-1.1.0.10
NI Simple Messaging (STM) Library-3.1.0.9
NI Modbus Library-1.2.1.42
NI Keyed Array Library-2.0.0.11
NI CVT Client Communication (CCC)-3.0.3.9
NI Current Value Table-3.3.0.13
NI Asynchronous Message Communication (AMC) Library-3.3.1.22
MGI User Interface-1.0.1.11
MGI Tree-1.0.4.4
MGI Tools-1.0.0.4
MGI Timing-1.1.0.2
MGI String-1.1.1.5
MGI Spline-1.1.0.1
MGI Read/Write Anything-2.1.4.4
MGI Picture & Image-1.0.2.1
MGI Numeric-1.1.0.2
MGI Menu Building-1.0.1.4
MGI Matrix & Vector-1.1.0.1
MGI Library-1.2.0.4
MGI Graph-1.0.2.6
MGI File-1.1.0.4
MGI Error Reporter-1.0.2.5
MGI Error Handling-1.1.1.3
MGI Coordinates-1.1.1.2
MGI Cluster-1.1.0.1
MGI Boolean-1.0.1.3
MGI Bezier-1.1.1.2
MGI Application Control-1.1.1.10
MGI 2D Array-1.1.1.5
MGI 1D Array-1.0.2.3
LUnit-1.4.26.17
LMock-1.1.1.6
LAVA Palette-1.0.0.1
LabVIEW Open Source Palette-1.0.2.7
jki_rsc_toolkits_palette-1.1-1
JKI State Machine-2018.0.7.45
JDP Science Common Utilities-1.4.1.18
i3 JSON-1.0.0.10
Epoch Date & Time-1.2.0.6
Cron Scheduler-1.1.0.14
Caraya Unit Test Framework-1.2.1.131

**Comment by antsundq** [comment]
Okay, so it seems my changes did not help at all. 

This is rather peculiar, it would be good if we can narrow it down in some way. Can I ask you to do a few experiments?

- try to open the class "C:\Program Files\National Instruments\LabVIEW 2020\vi.lib\Astemes\LUnit\LUnit Execution UI.lvclass" and see if there are any errors.
- Try creating a fresh test case in a new project, save it somewhere and try to run the tests. Just to rule out the example code as the offender. 
- if you could make a vipm configuration file from your system I can try to install the same packages here and see if there are conflicts. 
- Try to mass compile your whole vi.lib directory. It will take a few hours, but could potentially resolve the issue.

**Comment by antsundq** [comment]
Also, you could try to delete the content of c:/users/public/public documents/astemes/lunit 

This could help finding tests if something has corrupted the index used for test discovery.

**Comment by antsundq** [comment]
Yet one thing which came to mind, could you make sure LabVIEW has access to the public documents directory? Or in other words, if the C:\Users\Public\Documents\Astemes\LUnit directory is missing this would be a problem.

**Comment by antsundq** [comment]
Thanks for testing and sharing the results. I think we are narrowing it down some. 

You mentioned that a colleague of yours also see the same issue, and I have a suspicion that it might be something related to your company's IT policies which interfere when trying to use the public documents folder for application data. One difference, which did not occur to me earlier, when running a single class compared to using the run all entry point, is that the indexing feature is not used for single tests. 

I tried to change the location from public documents to C:\ProgramData\Astemes\LUnit for saving application data, this could potentially help. Would you mind trying it out: 
https://github.com/Astemes/astemes-lunit/releases/tag/v1.4.35

**Comment by napowelson** [comment]
I just tried the new version, and I'm seeing the same behavior as in my last post. :/

Which function is called when I click "Run All" in your code? I'm going to put in a breakpoint and walk it through until I crash. Then I can say exactly what is causing it...

**Comment by napowelson** [comment]
Ok, I found one instance where it's crashing LabVIEW, when clicking the "Run All" on the toolbar in my test project.

 I started probing in LUnit Find Tests.vi, and the VI that is crashing LabVIEW is "Test Suite.class:Remove.vi" in the "LUnit Test Finder.lvclass:LUnit Load Project Suite from Index.vi"
![image](https://github.com/Astemes/astemes-lunit/assets/51723349/763e93ab-768a-4659-82ab-23dcbc6456a2)

I made a change to it and it now no longer crashes, see attached remove.vi.
[Remove.zip](https://github.com/Astemes/astemes-lunit/files/15003051/Remove.zip)

It does still crash in the Inheritance project when I right-click run, if the test UI is open displaying other tests.  I'll look into that one a bit more too. But maybe they are related?

Using LabVIEW 20.0f1

**Comment by antsundq** [comment]
Well done there! 

So it seems like using an autoindexing for-loop over an empty map is crashing LabVIEW for you and at least someone else. I remember a similar problem about 5 years back when I started using maps on a cRIO and it made the RT application crash. I found a thread describing this issue, but this has never happened an windows. Maybe it is related though. 
https://forums.ni.com/t5/LabVIEW/LV-Real-time-crash-on-specific-map-use-with-objects/td-p/4012388

Just noticed that you are running LabVIEW 2020 64-bit, which I have not tried. Everything else with your setup should be fine. I will install this version on a test pc and try to reproduce this issue.

I integrated your fix to the remove.vi. A new release where this is fixed is available here:
https://github.com/Astemes/astemes-lunit/releases/tag/v1.4.36

/Anton

**Comment by antsundq** [comment]
I installed LV2020 64-bit and using this I can now reproduce this crash.
I have previously been using LabVIEW 2023 64-bit without problems, so this seems to be related to a bug in LabVIEW which has been fixed sometime between 2020 and 2023. But I think we'll be able to work around this now that I can reproduce the issue.

**Comment by antsundq** [comment]
I tried the fix to remove.vi, but I still see the crash. Will need to investigate this later.

**Comment by antsundq** [comment]
Hi,
I've been doing some testing and have a couple of conclusions. 

First, the two issues you are seeing (LabVIEW crashing and Test Inheritance project not loading) are related and I can reproduce both.

Second, it seems that this is due to some bug in LabVIEW which has been fixed in 2020 64-bit SP1. Using the 2020 64-bit SP1 version of LabVIEW, everything works well for me. But in the non-SP1 version I see the same crashes and issues as you do. 

My guess is that this is related to the use of maps of interfaces. but I have not been able to narrow it down. There is no mention of anything related in the buglist (https://www.ni.com/en/support/documentation/bugs/20/labview-2020-sp1-bug-fixes.html) either. 

So to solve this, there are two options. The implementation could be updated to avoid maps of interfaces, but this would require a significant amount of changes to the internals of LUnit. Or then we could make LabVIEW 2020 64-bit non-sp1 unsupported. 

Would you be able to upgrade to 2020 64-bit SP1? Having seen this. I think it would be a good idea in any case.

**Comment by napowelson** [comment]
Thanks, I was able to verify that your library works perfectly in LabVIEW 2021, so it's just our LV2020f1 installations that won't be able to use the library. Thanks again for your help to resolve the issue.

I recommend updating the LabVIEW compatibility of the library in VIPM, so you don't have any more unsuspecting victims of this strange bug.
